# Generated by Django 4.0 on 2022-01-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.FloatField()),
                ('scramble', models.CharField(max_length=300)),
                ('plusTwo', models.BooleanField()),
                ('DNF', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
