# Generated by Django 4.0 on 2022-03-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_tag_alter_session_eventtype_attempt_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='sessions')),
            ],
        ),
    ]
